title: Milen Dyankov
description: Software Engineer, Consultant, Developer Advocate
copyright: Milen Dyankov


url: "http://milendyankov.com"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:year/:month/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
excerpt_separator: <!--more-->

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Posts
   url: /posts
 - title: Talks
   url: /talks

social:
   email: milendyankov@gmail.com
   github: azzazzel
   googleplus: +MilenDyankov-profile
   lanyard: milendyankov
   linkedin: milendyankov
   picasaweb: 114975002325789911081
   prezi: c96dhku05hlx
   slideshare: MilenDyankov1
   slidrio: azzazzel
   twitter: milendyankov

google_analytics: "UA-6858591-2"
